Repository mint-lang/mint, pull requests merged in 2021-05, with the labels that each got.

#408 Sandbox server & `@inline` directive
  .github/workflows/ci.yml
  spec/compilers_spec.cr
  src/all.cr
  src/ast.cr
  src/ast/directives/asset.cr
  src/ast/directives/inline.cr
  src/builder.cr
  src/cli.cr
  src/commands/compile.cr
  src/commands/sandbox_server.cr
  src/compiler.cr
  src/compilers/directives/asset.cr
  src/compilers/directives/inline.cr
  src/compilers/top_level.cr
  src/formatters/directives/inline.cr
  src/messages/inline_directive_expected_closing_parentheses.cr
  src/messages/inline_directive_expected_file.cr
  src/messages/inline_directive_expected_opening_parentheses.cr
  src/messages/inline_directive_expected_path.cr
  src/parsers/basic_expression.cr
  src/parsers/directives/inline.cr
  src/reactor.cr
  src/sandbox_server.cr
  src/type_checkers/directives/inline.cr
Labels: enhancement, language, tooling

#426 Update enum destructuring to look like creating enums
  core/source/Array.mint
  core/source/Dom.mint
  core/source/Maybe.mint
  core/source/Provider/ElementSize.mint
  core/source/Provider/Intersection.mint
  core/source/Provider/Mutation.mint
  core/source/Result.mint
  core/source/Validation.mint
  spec/compilers/case_with_enum_destructuring
  spec/compilers/enum_record
  spec/formatters/enum_record
  spec/type_checking/access_call
  spec/type_checking/enum_record
  src/formatters/enum_destructuring.cr
  src/messages/enum_destructuring_expected_closing_parentheses.cr
  src/parsers/enum_destructuring.cr
Labels: language

#427 Abstract away differences between standards and quirks modes
  core/source/Window.mint
  core/tests/tests/Window.mint
  src/test_runner.ecr
Labels: bug

#429 [CI] Run core specs on both, firefox and chrome browsers
  .github/workflows/ci.yml
  core/tests/tests/Html/DataTransfer.mint
Labels: tooling

#428 Refactorings working towards nested destructuring
  src/ast/enum_destructuring.cr
  src/ast/tuple_destructuring.cr
  src/compilers/array_destructuring.cr
  src/compilers/case_branch.cr
  src/compilers/enum_destructuring.cr
  src/compilers/tuple_destructuring.cr
  src/parsers/enum_destructuring.cr
  src/parsers/tuple_destructuring.cr
  src/type_checkers/case_branch.cr
  src/type_checkers/scope.cr
Labels: enhancement, language

#436 Displayed the suite name of the failed test case.
  src/test_runner.cr
  src/test_runner.ecr
Labels: enhancement, tooling

#434 Set `Content-Type` header to `application/json` in `Http.jsonBody`
  core/source/Http.mint
  core/tests/tests/Http.mint
Labels: enhancement

#443 Show the filename and line number for each failed test
  src/ast.cr
  src/ast/node.cr
  src/builder.cr
  src/commands/compile.cr
  src/compilers/array_destructuring.cr
  src/compilers/html_element.cr
  src/compilers/suite.cr
  src/compilers/test.cr
  src/core.cr
  src/ls/server.cr
  src/lsp/protocol/text_document_position_params.cr
  src/sandbox_server.cr
  src/test_runner.cr
  src/test_runner.ecr
Labels: enhancement, tooling

#451 Add Inline Comment
  spec/formatters/if_with_comments
  spec/formatters/if_with_else_if_with_comment
  spec/formatters/inline_comment
  spec/formatters/inline_function_with_comments
  spec/parsers/comment_spec.cr
  src/ast/comment.cr
  src/formatters/comment.cr
  src/parsers/comment.cr
Labels: enhancement, language
