Repository mint-lang/mint, pull requests merged in 2021-06, with the labels that each got.

#454 Add `Maybe.withLazyDefault`
  core/source/Maybe.mint
  core/tests/tests/Dom.mint
  core/tests/tests/Maybe.mint
  core/tests/tests/Time.mint
Labels: enhancement, stdlib

#456 Enhance test assertions instrumentation
  src/compilers/parallel.cr
  src/compilers/sequence.cr
  src/compilers/test.cr
  src/compilers/try.cr
  src/test_runner.cr
Labels: enhancement, tooling

#460 #453 v2
  core/source/AnimationFrame.mint
  core/source/Provider/AnimationFrame.mint
  core/tests/tests/Provider/AnimationFrame.mint
Labels: enhancement, stdlib

#463 Add missing quote
  core/source/String.mint
Labels: documentation

#464 Fix `mint init` files not formatted with `mint format`
  src/app_init/app/source/Link.mint
  src/app_init/app/source/Logo.mint
Labels: refactor
