Repository mint-lang/mint, pull requests merged in 2021-07, with the labels that each got.

#467 Include css class name in compiled output
  spec/compilers/component_namespaced_with_style
  spec/compilers/css_definition
  spec/compilers/css_font_face
  spec/compilers/css_font_face_with_qoutes
  spec/compilers/css_keyframes
  spec/compilers/css_media
  spec/compilers/css_media_with_if
  spec/compilers/css_selector
  spec/compilers/css_selector_multiple
  spec/compilers/css_string
  spec/compilers/css_supports
  spec/compilers/css_with_ands
  spec/compilers/css_with_arguments
  spec/compilers/css_with_case
  spec/compilers/css_with_else_if
  spec/compilers/css_with_if
  spec/compilers/css_with_if_and_case
  spec/compilers/css_with_if_same_condition
  spec/compilers/html_attribute_class_with_style
  spec/compilers/html_with_multiple_styles
  spec/compilers/html_with_multiple_styles_and_parameters
  spec/compilers/html_with_multiple_styles_and_parameters_2
  spec/compilers/html_with_pseudos
  spec/compilers/html_with_style
  spec/compilers/html_with_style_and_custom_style
  spec/style_builder_spec.cr
  src/compiler.cr
  src/compilers/html_element.cr
  src/compilers/style.cr
  src/compilers/top_level.cr
  src/style_builder.cr
Labels: enhancement, language

#476 Feat: allow to swap runtime at compilation
  src/builder.cr
  src/cli.cr
  src/commands/build.cr
  src/commands/compile.cr
  src/commands/sandbox_server.cr
  src/commands/test.cr
  src/messages/runtime_file_not_found.cr
  src/sandbox_server.cr
  src/test_runner.cr
Labels: enhancement

#480 Fix a regression with `&` css selector name
  spec/compilers/html_with_pseudos
  spec/compilers/html_with_style
  src/parsers/css_selector.cr
Labels: regression
