Repository mint-lang/mint, pull requests merged in 2023-09, with the labels that each got.

#636 LSP: Add Go To Definition support for `Ast::Access`
  spec/language_server/definition/location/access_array
  spec/language_server/definition/location/access_call
  spec/language_server/definition/location/access_record_multiple
  spec/language_server/definition/location/access_record_single
  spec/language_server/definition/location_link/access_array
  spec/language_server/definition/location_link/access_call
  spec/language_server/definition/location_link/access_record_multiple
  spec/language_server/definition/location_link/access_record_single
  src/ls/definition/access.cr
  src/parsers/access.cr
Labels: enhancement, tooling

#618 Localization Language Feature
  core/source/Locale.mint
  documentation/Language/Locale.md
  spec/compilers/locale_key
  spec/formatters/locale
  spec/formatters/locale_key
  spec/parsers/locale_key_spec.cr
  spec/parsers/locale_spec.cr
  spec/type_checking/locale_key
  src/ast.cr
  src/ast/component.cr
  src/ast/locale.cr
  src/ast/locale_key.cr
  src/compiler.cr
  src/compilers/component.cr
  src/compilers/locale_key.cr
  src/compilers/top_level.cr
  src/formatters/locale.cr
  src/formatters/locale_key.cr
  src/formatters/top_level.cr
  src/messages/expected_end_of_file.cr
  src/messages/locale_expected_closing_bracket.cr
  src/messages/locale_expected_language.cr
  src/messages/locale_expected_opening_bracket.cr
  src/messages/translation_mismatch.cr
  src/messages/translation_missing.cr
  src/messages/translation_not_translated.cr
  src/parser.cr
  src/parsers/basic_expression.cr
  src/parsers/component.cr
  src/parsers/locale.cr
  src/parsers/locale_key.cr
  src/parsers/top_level.cr
  src/type_checker.cr
  src/type_checker/artifacts.cr
  src/type_checker/scope.cr
  src/type_checkers/locale.cr
  src/type_checkers/locale_key.cr
Labels: language

#625 Named Arguments
  documentation/Language/Locale.md
  spec/compilers/call_labelled
  spec/type_checking/function_call_labelled
  src/ast/call.cr
  src/ast/call_expression.cr
  src/ast/pipe.cr
  src/compiler.cr
  src/compilers/block.cr
  src/compilers/call.cr
  src/compilers/call_expression.cr
  src/formatters/call_expression.cr
  src/messages/call_not_found_argument.cr
  src/messages/call_with_mixed_arguments.cr
  src/parsers/call.cr
  src/parsers/call_expression.cr
  src/type_checker.cr
  src/type_checker/artifacts.cr
  src/type_checker/comparer.cr
  src/type_checker/record.cr
  src/type_checker/type.cr
  src/type_checker/variable.cr
  src/type_checkers/argument.cr
  src/type_checkers/call.cr
  src/type_checkers/case.cr
Labels: enhancement, language

#660 Added bindings to the Console API.
  core/source/Console.mint
  core/tests/tests/Console.mint
Labels: enhancement, stdlib

#663 Combine `Provider.Keydown` and `Provider.Keyup` into `Provider.Keyboard`
  core/source/Provider/Keyboard.mint
  core/source/Provider/Keydown.mint
  core/source/Provider/Keyup.mint
  core/source/Test/Html.mint
  core/tests/tests/Provider/Keyboard.mint
Labels: stdlib, refactor

#668 Added formatter for font-face css feature.
  spec/formatters/font_face
  src/formatters/css_font_face.cr
Labels: bug, tooling

#669 Allow asyncronhous tests.
  core/tests/tests/Test.mint
  spec/errors/test_type_mismatch
  spec/examples/test
  src/compilers/test.cr
  src/type_checker.cr
  src/type_checkers/test.cr
Labels: enhancement, tooling

#673 Test runner improvements.
  src/commands/test.cr
  src/render/terminal.cr
  src/test_runner.cr
  src/test_runner.ecr
  src/test_runner/documentation_reporter.cr
  src/test_runner/dot_reporter.cr
  src/test_runner/reporter.cr
  src/utils/server.cr
Labels: enhancement, tooling

#674 Implement @highlight-file directive.
  spec/compilers/directives/highlight-file
  spec/examples/directives/highlight_file
  spec/fixtures/Test.mint
  spec/formatters/directives/highlight-file
  src/ast/directives/file_based.cr
  src/compilers/directives/highlight_file.cr
  src/formatters/directives/highlight_file.cr
  src/parsers/base_expression.cr
  src/parsers/directives/highlight_file.cr
  src/scope.cr
  src/type_checkers/directives/highlight_file.cr
Labels: language

#675 Improve Development Server
  src/reactor.cr
  src/type_checker.cr
  src/type_checkers/top_level.cr
  src/workspace.cr
Labels: bug, enhancement, tooling

#676 Extra build mode flags: `--skip-manifest`, `--inline`, and `--watch`
  src/builder.cr
  src/commands/build.cr
  src/utils/index_html.cr
  src/utils/index_html.ecr
Labels: enhancement, tooling
