Repository mint-lang/mint, pull requests merged in 2023-05, with the labels that each got.

#591 LSP: Add tests for hover feature
  spec/language_server/hover/argument
  spec/language_server/hover/css_definition
  spec/language_server/hover/enum
  spec/language_server/hover/enum_destructuring
  spec/language_server/hover/enum_id
  spec/language_server/hover/enum_option
  spec/language_server/hover/function_component
  spec/language_server/hover/function_module
  spec/language_server/hover/function_provider
  spec/language_server/hover/function_store
  spec/language_server/hover/get
  spec/language_server/hover/html_attribute
  spec/language_server/hover/html_component
  spec/language_server/hover/html_element
  spec/language_server/hover/module_access
  spec/language_server/hover/property
  spec/language_server/hover/state
  spec/language_server/hover/statement
  spec/language_server/hover/string_literal
  spec/language_server/hover/type_enum
  spec/language_server/hover/type_record
  spec/language_server/hover_spec.cr
  spec/language_server/ls_spec.cr
Labels: tooling

#593 Nested Destructuring
  spec/compilers/case
  spec/compilers/case_empty
  spec/compilers/case_with_array_destructuring
  spec/compilers/case_with_enum_destructuring
  spec/compilers/case_with_nested_tuple_destructuring
  spec/compilers/case_with_tuple_destructuring
  spec/compilers/case_with_tuple_destructuring_bool
  spec/compilers/component_instance_access
  spec/compilers/css_with_case
  spec/compilers/css_with_if_and_case
  spec/compilers/enum_record
  spec/compilers/if_let
  spec/compilers/inline_function_recursive
  spec/compilers/inline_functions_recursive
  spec/type_checking/case_branch
  spec/type_checking/if_let
  spec/type_checking/statement
  src/compilers/array_destructuring.cr
  src/compilers/case.cr
  src/compilers/case_branch.cr
  src/compilers/destructuring.cr
  src/compilers/enum_destructuring.cr
  src/compilers/if.cr
  src/compilers/top_level.cr
  src/compilers/tuple_destructuring.cr
  src/messages/case_branch_not_array.cr
  src/messages/case_branch_not_tuple.cr
  src/messages/destructuring_multiple_spreads.cr
  src/messages/destructuring_no_parameter.cr
  src/messages/destructuring_tuple_mismatch.cr
  src/messages/destructuring_type_mismatch.cr
  src/messages/enum_destructuring_enum_missing.cr
  src/messages/enum_destructuring_type_missing.cr
  src/messages/statement_not_match_expression.cr
  src/messages/statement_not_tuple.cr
  src/messages/statement_tuple_mismatch.cr
  src/parsers/array_destructuring.cr
  src/parsers/case_branch.cr
  src/parsers/destructuring.cr
  src/parsers/enum_destructuring.cr
  src/parsers/tuple_destructuring.cr
  src/parsers/variable.cr
  src/type_checker/scope.cr
  src/type_checkers/case.cr
  src/type_checkers/case_branch.cr
  src/type_checkers/destructuring.cr
  src/type_checkers/enum_destructuring.cr
  src/type_checkers/if.cr
  src/type_checkers/statement.cr
Labels: enhancement, language

#597 LSP: Add Go to Definition support for Enum/Type/Connect
  spec/language_server/definition/core_component
  spec/language_server/definition/location/connect
  spec/language_server/definition/location/connect_variable_constant
  spec/language_server/definition/location/connect_variable_function
  spec/language_server/definition/location/connect_variable_get
  spec/language_server/definition/location/connect_variable_state
  spec/language_server/definition/location/enum_destructuring_name
  spec/language_server/definition/location/enum_destructuring_option
  spec/language_server/definition/location/enum_id_name
  spec/language_server/definition/location/enum_id_option
  spec/language_server/definition/location/type_enum
  spec/language_server/definition/location/type_record
  spec/language_server/definition/location_link/connect
  spec/language_server/definition/location_link/connect_variable_constant
  spec/language_server/definition/location_link/connect_variable_function
  spec/language_server/definition/location_link/connect_variable_get
  spec/language_server/definition/location_link/connect_variable_state
  spec/language_server/definition/location_link/enum_destructuring_name
  spec/language_server/definition/location_link/enum_destructuring_option
  spec/language_server/definition/location_link/enum_id_name
  spec/language_server/definition/location_link/enum_id_option
  spec/language_server/definition/location_link/type_enum
  spec/language_server/definition/location_link/type_record
  src/ls/definition/connect.cr
  src/ls/definition/connect_variable.cr
  src/ls/definition/enum_destructuring.cr
  src/ls/definition/enum_id.cr
  src/ls/definition/type.cr
Labels: enhancement, tooling

#599 Fix comment being included in `case_enum_not_covered` message
  src/type_checkers/case.cr
Labels: bug

#598 Allow `else` branch to be omitted in certain cases.
  spec/compilers/if_without_else_array
  spec/compilers/if_without_else_promise
  spec/compilers/if_without_else_string
  spec/compilers/next_call_empty
  spec/parsers/if_spec.cr
  src/compilers/if.cr
  src/compilers/next_call.cr
  src/messages/if_expected_else.cr
  src/parsers/html_body.cr
  src/parsers/if.cr
  src/type_checker.cr
  src/type_checkers/case_branch.cr
  src/type_checkers/comment.cr
  src/type_checkers/component.cr
  src/type_checkers/connect.cr
  src/type_checkers/css_definition.cr
  src/type_checkers/css_font_face.cr
  src/type_checkers/css_keyframes.cr
  src/type_checkers/css_nested_at.cr
  src/type_checkers/css_selector.cr
  src/type_checkers/destructuring.cr
  src/type_checkers/html_content.cr
  src/type_checkers/html_style.cr
  src/type_checkers/if.cr
  src/type_checkers/module.cr
  src/type_checkers/provider.cr
  src/type_checkers/routes.cr
  src/type_checkers/store.cr
  src/type_checkers/style.cr
  src/type_checkers/suite.cr
  src/type_checkers/test.cr
  src/type_checkers/top_level.cr
  src/type_checkers/variable.cr
Labels: enhancement, language

#604 Some fixes
  core/source/Window.mint
  documentation/Core/Conventions/Naming.md
Labels: documentation

#603 Add `Url.toString()` API function
  core/source/Url.mint
  core/tests/tests/Url.mint
Labels: stdlib

#608 Update record syntax in examples
  core/source/Dom.mint
  core/source/WebSocket.mint
Labels: bug, documentation

#610 Replace reject with resolve
  core/source/Window.mint
Labels: bug, stdlib
