Repository mint-lang/mint, pull requests merged in 2023-08, with the labels that each got.

#626 Update documentation of `Object.Decode` functions
  core/source/Object/Decode.mint
Labels: documentation

#630 Fix keywords and operators being kept when parsing a parent node fails
  spec/language_server/semantic_tokens/component
  src/parser.cr
Labels: bug, tooling

#628 LSP: Fix enum destructuring/id linking to other types with the same name
  spec/language_server/definition/location_link/enum_destructuring_option
  spec/language_server/definition/location_link/enum_id_option
  src/parsers/enum_destructuring.cr
  src/parsers/enum_id.cr
Labels: bug, tooling

#631 Add missing Math constants and functions
  .gitignore
  core/source/Math.mint
  core/tests/tests/Math.mint
Labels: enhancement, stdlib
