Repository mint-lang/mint, pull requests merged in 2025-03, with the labels that each got.

#745 Better windows compatibility
  shard.lock
  shard.yml
  src/command.cr
  src/test_runner/browser.cr
Labels: enhancement

#749 Implement function captures.
  spec/compilers/call_captured
  spec/compilers/call_labelled_captured
  spec/examples/call
  src/compilers/call.cr
  src/parsers/call.cr
  src/parsers/field.cr
  src/type_checkers/call.cr
Labels: language

#753 Adds `Array.all` function
  core/source/Array.mint
  core/tests/tests/Array.mint
Labels: stdlib
